import { useState } from 'react';
import type { Comparison, Rfx } from './contract';
import './award-decision-workspace.css';

type Props = { rfx: Rfx | null; comparison: Comparison | null; proposal: any; approved: boolean; busy: boolean; onRecommend: () => void; onApprove: (rationale: string) => void; onDisable: (label: string) => void };

function readable(value: any): string { if (typeof value === 'string') return value; if (!value || typeof value !== 'object') return String(value ?? ''); return value.claim || value.detail || value.description || value.reason || value.text || Object.entries(value).filter(([key]) => !['path', 'source', 'url'].includes(key)).map(([key, item]) => `${key}: ${readable(item)}`).join(' · '); }

export default function AwardDecisionWorkspace({ rfx, comparison, proposal, approved, busy, onRecommend, onApprove, onDisable }: Props) {
  const [rationale, setRationale] = useState('');
  if (!rfx || !comparison) return <section className="workspace"><div className="panel empty"><h2>Completed comparison required</h2><p>Finish the comparison analysis before preparing an award recommendation.</p></div></section>;
  const recommendation = proposal?.supplier ? proposal : null;
  return <section className="workspace award-screen">
    <div className="kicker">05 / DECIDE AND DEFEND AWARD</div><h1>Make the right decision with the trade-offs in view.</h1><p className="lede">Aera applies the approved criteria and drafts the reasoning for your review.</p>
    <section className="panel decision-basis"><div className="section-title"><h3>Decision basis</h3><span>Approved RFx criteria</span></div><p>Comparable cost 50% · quality 30% · delivery 20%</p><a href={`/demo-runtime/${comparison.policyBasis?.[0]?.path?.replace('/demo-runtime/', '') || 'sources/policy/procurement-policy-fy2026.html'}`} target="_blank" rel="noreferrer">View the policy basis ↗</a><div className="disabled-actions"><button onClick={() => onDisable('Change decision criteria')}>Change decision criteria <small>Disabled for this demo</small></button><button onClick={() => onDisable('Choose no award')}>Choose no award <small>Disabled for this demo</small></button></div></section>
    {!recommendation && <section className="panel recommendation-start"><div><h2>Prepare the award recommendation.</h2><p>Aera will apply the approved RFx criteria to the completed comparison and show the supporting evidence.</p></div><button className="primary" onClick={onRecommend} disabled={busy}>{busy ? 'Aera is reviewing the comparison…' : 'Prepare recommendation'}</button></section>}
    {recommendation && <>
      <section className="panel recommendation-card"><div className="agent-line"><span className="agent-mark">A</span><div><b>Aera · award recommendation</b><small>Proposal based on the approved comparison</small></div><span className="tag">Buyer decision required</span></div><div className="recommended-supplier"><span className="kicker">PROPOSED SUPPLIER</span><h2>{recommendation.supplier}</h2><p>{readable(recommendation.recommendation) || 'Aera proposes this supplier based on the approved evaluation basis.'}</p></div><div className="tradeoff-grid"><div><h3>Trade-offs</h3><ul>{(Array.isArray(recommendation.tradeoffs) ? recommendation.tradeoffs : [recommendation.tradeoffs]).filter(Boolean).map((item: any, index: number) => <li key={`${readable(item)}-${index}`}>{readable(item)}</li>)}</ul></div><div><h3>Evidence</h3><ul>{(Array.isArray(recommendation.evidence) ? recommendation.evidence : [recommendation.evidence]).filter(Boolean).map((item: any, index: number) => <li key={`${readable(item)}-${index}`}><span>{readable(item)}</span>{item && typeof item === 'object' && (item.path || item.source) && <a href={item.path || item.source} target="_blank" rel="noreferrer">View source ↗</a>}</li>)}</ul><div className="evidence-links"><a href="/demo-runtime/sources/rfx-2026-014.pdf" target="_blank" rel="noreferrer">Approved RFx ↗</a><a href="/demo-runtime/sources/policy/procurement-policy-fy2026.html" target="_blank" rel="noreferrer">Policy ↗</a></div></div></div></section>
      <section className="panel rationale-section"><div className="section-title"><h3>Aera’s draft rationale</h3><span>Review and edit</span></div><p>Use this explanation to record why the approved award basis supports your decision.</p><textarea value={rationale || recommendation.rationale || ''} onChange={event => setRationale(event.target.value)} aria-label="Award rationale"/><div className="approval-row"><span>{approved ? 'Award approved and recorded.' : 'Your approval is required to complete the sourcing thread.'}</span><button className="primary" onClick={() => onApprove(rationale || recommendation.rationale || '')} disabled={approved || busy || !(rationale || recommendation.rationale)?.trim()}>{approved ? 'Award approved' : busy ? 'Recording approval…' : 'Approve award'}</button></div></section>
    </>}
  </section>;
}
