import { useState } from 'react';
import type { Comparison, Rfx } from './contract';
import './comparison-workspace.css';

type Props = { rfx: Rfx | null; comparison: Comparison | null; busy: boolean; question: string; analysis: string; ack: boolean; onLoad: () => void; onAsk: () => void; onQuestion: (value: string) => void; onAck: (value: boolean) => void; onContinue: () => void };

export default function ComparisonWorkspace({ rfx, comparison, busy, question, analysis, ack, onLoad, onAsk, onQuestion, onAck, onContinue }: Props) {
  const [selected, setSelected] = useState(0);
  const samplePrompts = ['Which suppliers cover all 30 lines?', 'How do the normalized totals compare?', 'What delivery differences should I examine?', 'Which claims need source review?'];
  if (!rfx) return <section className="workspace"><div className="panel empty"><h2>Approved RFx required</h2><p>Complete the earlier sourcing steps before opening the comparison.</p></div></section>;
  if (!comparison) return <section className="workspace comparison-screen"><div className="kicker">03 / COMPARE RESPONSES</div><h1>Compare responses.</h1><p className="lede">Understand every supplier offer on the same basis before you make the award decision.</p><div className="panel comparison-entry"><div><b>Comparison is ready to open.</b><p>Supplier responses, extracted values, evidence, and policy treatment are available for review.</p></div><button className="primary" onClick={onLoad} disabled={busy}>{busy ? 'Building comparison…' : 'Open comparison'}</button></div></section>;
  const rows = Array.isArray(comparison.suppliers) ? comparison.suppliers : [];
  const warnings = Array.isArray(comparison.warnings) ? comparison.warnings : [];
  const current = rows[selected] || rows[0];
  const ready = comparison.ready === true;
  return <section className="workspace comparison-screen">
    <div className="kicker">03 / COMPARE RESPONSES</div><h1>Compare responses.</h1><p className="lede">Understand every supplier offer on the same basis before you make the award decision.</p>
    <div className="comparison-status"><div><b>{comparison.aiReview === 'pending' ? 'Comparison is open. Aera is checking the evidence.' : ready ? 'Comparison ready for analysis.' : 'Comparison needs attention.'}</b><p>{comparison.aiReview === 'pending' ? 'The table is ready now; the live evidence review will update exceptions as it completes.' : ready ? 'The values below are normalized with their original evidence preserved.' : 'Review the cited exceptions and source evidence before continuing.'}</p></div><span className={ready ? 'tag' : 'response-state needs-clarification'}>{comparison.aiReview === 'pending' ? 'Reviewing' : ready ? 'Ready' : 'Review required'}</span></div>
    <div className="panel comparison"><div className="section-title"><h3>Side-by-side comparison</h3><span>5 suppliers · 30 lines · {comparison.comparisonCurrency || 'INR'} comparison basis</span></div>
      {warnings.length > 0 && <div className="warning"><b>Exceptions requiring attention</b>{warnings.map((warning, index) => <p key={`${warning}-${index}`}>{warning}</p>)}</div>}
      {rows.length ? <table><thead><tr><th>Supplier</th><th>Evaluated total</th><th>Line coverage</th><th>Response state</th></tr></thead><tbody>{rows.map((supplier: any, index) => <tr className={index === selected ? 'selected-row' : ''} key={`${supplier?.name || 'supplier'}-${index}`} onClick={() => setSelected(index)}><td><strong>{supplier?.name || 'Supplier not identified'}</strong><small>{supplier?.originalCurrency && supplier.originalCurrency !== supplier.currency ? `${supplier.originalCurrency} original · normalized to ${supplier.currency}` : `${supplier?.currency || 'Currency pending'} · select to inspect evidence`}</small></td><td>{supplier?.currency || '—'} {typeof supplier?.total === 'number' ? supplier.total.toLocaleString() : '—'}</td><td>{typeof supplier?.lines === 'number' ? supplier.lines : '—'} / {comparison.lines?.length || 30} lines</td><td><span className="tag">{supplier?.completeness || 'Review required'}</span></td></tr>)}</tbody></table> : <div className="inline-error">The comparison response did not contain supplier rows. Reopen the comparison to retry.</div>}
      {current && <div className="evidence-drawer"><div><b>{current.name} · source evidence</b><p>Every extracted value remains linked to the response record used to construct this row.</p></div><div className="evidence-links">{(Array.isArray(current.evidence) ? current.evidence : []).map((source: any, index: number) => <a href={source.path || '#'} target="_blank" rel="noreferrer" key={`${source.path}-${index}`}><span>{source.kind || 'FILE'}</span>{source.label || source}</a>)}</div>{Array.isArray(current.claims) && <details><summary>View {current.claims.length} line-level claims</summary><div className="claim-list">{current.claims.slice(0, 30).map((claim: any) => <div key={claim.lineId}><b>{claim.lineId}</b><span>{claim.normalizedCurrency || claim.currency} {claim.normalizedPrice ?? '—'} / {claim.unit || 'unit'}</span><a href={`/demo-runtime/${claim.source}`} target="_blank" rel="noreferrer">source</a></div>)}</div></details>}</div>}
      <p className="comparison-source">Normalization basis: <a href={`/demo-runtime/${comparison.fx?.source || 'sources/finance/northstar-finance-fx-rate-sheet.html'}`} target="_blank" rel="noreferrer">Finance FX rate sheet</a> · {comparison.fx?.rate || '—'} · original values preserved.</p>
    </div>
    <div className="panel analysis"><div className="section-title"><h3>Understand the comparison</h3><span>Analysis only</span></div><p className="callout">Use this space to understand the offers, trade-offs, exceptions, and evidence. Award recommendation comes next.</p><div className="sample-prompts"><span>Start with a question</span><div>{samplePrompts.map(prompt => <button key={prompt} onClick={() => { onQuestion(prompt); }} disabled={busy}>{prompt}</button>)}</div></div><div className="question"><input value={question} onChange={e => onQuestion(e.target.value)} placeholder="Ask about price, coverage, delivery, quality, terms, or evidence"/><button className="secondary" onClick={onAsk} disabled={!question || busy}>Ask Aera</button></div>{analysis && <div className="answer">{analysis}</div>}<label className="checkbox"><input type="checkbox" checked={ack} onChange={e => onAck(e.target.checked)} disabled={!ready}/><span>I acknowledge that the comparison and resulting analysis are accurate and sufficient for award recommendation.</span></label><button className="primary" disabled={!ack || !ready} onClick={onContinue}>Continue to award decision</button></div>
  </section>;
}
