import { useEffect, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { contract, type Issue, type Rfx, type Stage } from './contract';
import SupplierExchangeWorkspace from './SupplierExchangeWorkspace';
import ComparisonWorkspace from './ComparisonWorkspace';
import AwardDecisionWorkspace from './AwardDecisionWorkspace';
import { businessNeed, preparedSources, sourceUrl, suppliers } from './runtime';
import './styles.css';

const post = async (url: string, payload: unknown) => { const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const raw = await response.text(); let data: any = {}; try { data = raw ? JSON.parse(raw) : {}; } catch { throw new Error(`The service returned an invalid response (${response.status}).`); } if (!response.ok || data.error) throw new Error(data.error || 'Request failed'); return data; };
const storageKey = 'aerchain-demo-progress';
function loadProgress() { try { const reset = new URLSearchParams(window.location.search).get('reset'); if (reset === '1' || reset === 'true') { localStorage.removeItem(storageKey); window.history.replaceState({}, document.title, window.location.pathname); return {}; } const value = JSON.parse(localStorage.getItem(storageKey) || '{}'); if (value.schemaVersion !== 2) return {}; if (value.stage > 1 && !value.rfx) return {}; if (value.stage > 3 && (!value.comparison || value.ack !== true)) return {}; return value; } catch { return {}; } }

function App() {
  const initial = loadProgress();
  const [stage, setStage] = useState<Stage>(initial.stage ?? 0); const [rfx, setRfx] = useState<Rfx | null>(initial.rfx ?? null); const [comparison, setComparison] = useState<any>(initial.comparison ?? null); const [completeness, setCompleteness] = useState<any>(initial.completeness ?? null); const [analysis, setAnalysis] = useState(initial.analysis ?? ''); const [question, setQuestion] = useState(initial.question ?? ''); const [proposal, setProposal] = useState<any>(initial.proposal ?? null); const [ack, setAck] = useState(Boolean(initial.ack)); const [approved, setApproved] = useState(Boolean(initial.approved)); const [askConfirmed, setAskConfirmed] = useState(Boolean(initial.askConfirmed)); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { try { localStorage.setItem(storageKey, JSON.stringify({ schemaVersion: 2, stage, rfx, comparison, completeness, analysis, question, proposal, ack, approved, askConfirmed })); } catch { /* browser persistence is best effort in this demo */ } }, [stage, rfx, comparison, completeness, analysis, question, proposal, ack, approved, askConfirmed]);
  const run = async (fn: () => Promise<void>) => { setBusy(true); setError(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Something went wrong'); } finally { setBusy(false); } };
  const createRfx = () => run(async () => { const sources: Record<string, string> = {}; const sourceFiles: any[] = []; for (const source of preparedSources) { if (/\.(xlsx|docx|pdf)$/i.test(source.path)) sourceFiles.push({ name: source.name, path: source.path, mime: source.path.endsWith('.xlsx') ? 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' : 'application/pdf', note: source.description }); else sources[source.name] = await (await fetch(sourceUrl(source.path))).text(); } const result = await post('/api/intake', { businessNeed, sources, sourceFiles }); setRfx(result.rfx); });
  const approveRfx = () => { if (!rfx) return; if (rfx.issues?.some(issue => issue.status === 'open')) return setNotice('Resolve the open RFx treatment before approval.'); setNotice('RFx approved and ready for supplier invitation.'); setStage(2); };
  const reviewResponses = (reassess = false) => run(async () => { if (!rfx) return; const result = await post('/api/completeness', { rfx, reassess }); setCompleteness(result.completeness); });
  const approveFollowUp = (supplier: string) => { setNotice(`Follow-up approved for ${supplier}. Aera is reassessing the prepared reply.`); void reviewResponses(true); };
  const loadComparison = () => run(async () => { if (!rfx) return; const result = await post('/api/comparison', { rfx }); setComparison(result.comparison); setBusy(false); void post('/api/comparison-review', { rfx, comparison: result.comparison }).then(review => setComparison((current: any) => current ? { ...current, warnings: review.findings.map((finding: any) => `${finding.supplier}: ${finding.title} — ${finding.detail}`), exceptions: review.findings, ready: review.ready === true, decisionReady: review.ready === true, status: review.status, aiReview: 'complete' } : current)).catch(() => setComparison((current: any) => current ? { ...current, aiReview: 'failed', warnings: ['Live evidence review could not complete; retry required.'] } : current)); });
  const confirmIssue = (id: string) => setRfx(current => current ? { ...current, issues: current.issues.map(issue => issue.id === id ? { ...issue, status: 'confirmed' } : issue) } : current);
  const confirmSupplierPoint = (label: string) => { const match = label.match(/^Confirm treatment for (.+): (.+)$/); if (!match) return; const [, supplier, title] = match; setCompleteness((current: any) => current ? { ...current, suppliers: current.suppliers.map((row: any) => { if (row.name !== supplier) return row; const openPoints = (row.openPoints || []).filter((point: any) => point.title !== title); return { ...row, openPoints, state: openPoints.length ? row.state : 'complete', nextAction: openPoints.length ? 'Review the remaining open points.' : 'All identified response conditions are confirmed.', history: [...(row.history || []), { label: `Buyer-confirmed treatment: ${title}`, status: 'confirmed' }] }; }), aggregateState: current.suppliers.every((row: any) => row.name === supplier ? (row.openPoints || []).filter((point: any) => point.title !== title).length === 0 : ['complete', 'resolved', 'policy-authorized-exception'].includes(row.state)) ? 'resolved' : current.aggregateState } : current); setNotice(`Treatment confirmed for ${supplier}. Readiness updated below.`); };
  const disabled = (label: string) => { if (label.startsWith('Confirm treatment for ')) return confirmSupplierPoint(label); setNotice(`${label} is disabled for this prepared demo.`); };
  const ask = () => run(async () => { if (!comparison) return; const result = await post('/api/analyze', { rfx, comparison, question }); setAnalysis(result.answer); });
  const recommend = () => run(async () => { if (!comparison?.decisionReady) throw new Error('Comparison acknowledgment is required before award recommendation.'); const result = await post('/api/award', { rfx, comparison, buyerGuidance: 'Apply the approved RFx criteria and explain the trade-offs.' }); setProposal(result.proposal); });
  const commitAward = (rationale: string) => run(async () => { const result = await post('/api/award-commit', { rfx, comparison, proposal, rationale, idempotencyKey: `demo:${comparison?.event}:${proposal?.supplier}:${rationale}` }); setApproved(true); setNotice(`Award approved. Record ${result.record.recordId} committed in the demo process store.`); });
  return <div className="app"><header className="topbar"><div className="brand"><span className="mark">A</span><span>Aera</span><small>AI SOURCING AGENT</small></div><nav>{['Start', 'Create RFx', 'Lock responses', 'Compare responses', 'Decide & defend'].map((label, index) => <button key={label} className={stage === index ? 'active' : ''} onClick={() => index <= stage && setStage(index as Stage)}>{String(index).padStart(2, '0')} {label}</button>)}</nav></header><main>
    {stage === 0 && <Landing onStart={() => setStage(1)} />}
    {stage === 1 && <RfxScreen rfx={rfx} askConfirmed={askConfirmed} busy={busy} onConfirmAsk={() => setAskConfirmed(true)} onCreate={createRfx} onConfirmIssue={confirmIssue} onApprove={approveRfx} />}
    {stage === 2 && <SupplierExchangeWorkspace rfx={rfx} completeness={completeness} busy={busy} onReview={reviewResponses} onDisable={disabled} onApproveFollowUp={approveFollowUp} onContinue={() => setStage(3)} />}
    {stage === 3 && <ComparisonWorkspace rfx={rfx} comparison={comparison} busy={busy} question={question} analysis={analysis} ack={ack} onLoad={loadComparison} onAsk={ask} onQuestion={setQuestion} onAck={setAck} onContinue={() => setStage(4)} />}
    {stage === 4 && <AwardDecisionWorkspace rfx={rfx} comparison={comparison} proposal={proposal} approved={approved} busy={busy} onRecommend={recommend} onApprove={commitAward} onDisable={disabled} />}
  </main>{(error || notice) && <div className={error ? 'toast error' : 'toast'} onClick={() => { setError(''); setNotice(''); }}>{error || notice}<span>×</span></div>}</div>;
}

function Landing({ onStart }: { onStart: () => void }) { return <><section className="landing" style={{ display: 'block', maxWidth: 1180 }}><div className="landing-copy"><Kicker>{contract.hero.eyebrow}</Kicker><h1>{contract.hero.headline}</h1><p className="hero-sub">{contract.hero.supporting}</p><button className="primary" onClick={onStart}>{contract.demo.heroCta} <span>→</span></button></div></section><section className="pain-relief" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', padding: '0 5vw', background: '#fff' }}><div style={{ padding: '25px 5vw 65px 0' }}><h3>{contract.hero.trackHeaders[0]}</h3>{contract.hero.tracks.map(([left]) => <p className="track-line" key={left}>{left}</p>)}</div><div style={{ padding: '25px 0 65px 5vw', borderLeft: '1px solid #dededb' }}><h3>{contract.hero.trackHeaders[1]}</h3>{contract.hero.tracks.map(([, right]) => <p className="track-line" key={right}>{right}</p>)}</div></section><section className="workflow"><Kicker>{contract.workflow.heading}</Kicker><div className="workflow-grid">{contract.workflow.steps.map(([number, title, description]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="demo-band"><Kicker>{contract.demo.eyebrow}</Kicker><h2>{contract.demo.line}</h2><button className="primary" onClick={onStart}>{contract.demo.bottomCta} <span>→</span></button></section></>; }
function RfxScreen({ rfx, askConfirmed, busy, onConfirmAsk, onCreate, onConfirmIssue, onApprove }: { rfx: Rfx | null; askConfirmed: boolean; busy: boolean; onConfirmAsk: () => void; onCreate: () => void; onConfirmIssue: (id: string) => void; onApprove: () => void }) { return <section className="workspace rfx-screen"><Kicker>01 / CREATE AND APPROVE RFx</Kicker><h1>Create and approve RFx</h1><p className="lede">Turn the business need and authorized sources into an RFx you can review, correct, and approve for supplier invitation.</p><div className="panel intake-section"><SectionTitle title="State the procurement ask" meta={rfx ? 'RFx review in progress' : askConfirmed ? 'Ask confirmed' : 'Ready for confirmation'} /><div className="need">{businessNeed}</div><button className="primary" disabled={busy || Boolean(rfx?.issues?.some(issue => issue.status === 'open'))} onClick={() => rfx ? onApprove() : askConfirmed ? onCreate() : onConfirmAsk()}>{busy ? 'Aera is shaping the RFx…' : rfx ? 'Approve RFx' : askConfirmed ? 'Generate draft RFx' : 'Confirm Procurement Ask'}</button>{rfx && <RfxReview rfx={rfx} onConfirm={onConfirmIssue} onApprove={onApprove} />}</div><div className="panel source-section"><SectionTitle title="Sources for this RFx" meta="Prepared demo set" /><div className="source-list">{preparedSources.map(source => <div className="source" key={source.name}><div><strong>{source.name}</strong><small>{source.type} · {source.description}</small></div><a href={sourceUrl(source.path)} target="_blank" rel="noreferrer">View</a></div>)}</div></div></section>; }
function RfxReview({ rfx, onConfirm, onApprove }: { rfx: Rfx; onConfirm: (id: string) => void; onApprove: () => void }) { const open = rfx.issues.filter(issue => issue.status === 'open'); return <div className="rfx-review"><div className="draft-intro"><div><Kicker>RFx draft</Kicker><h2>{rfx.title}</h2><p>{rfx.scope}</p></div><span className="draft-status">Draft · buyer review</span></div><ReviewSection title="Scope and boundaries" support="What suppliers are being asked to provide"><p>{rfx.objective || rfx.scope}</p></ReviewSection><ReviewSection title="Line items" support="Confirm what suppliers must quote"><div className="line-table">{(rfx.items || []).map((item, index) => <div className="line-row" key={`${item.name}-${index}`}><span>L-{String(index + 1).padStart(2, '0')}</span><strong>{item.name}</strong><span>{item.quantity}</span><span>{item.unit}</span></div>)}</div></ReviewSection><ReviewSection title="Questionnaire and terms" support="Confirm supplier response expectations"><ul className="review-list">{[...(rfx.questionnaire || []), ...(rfx.terms || [])].map((item, index) => <li key={`${item}-${index}`}><span>✓</span>{item}</li>)}</ul></ReviewSection><div className="issues"><SectionTitle title="Issues and assumptions" meta={open.length ? `${open.length} open` : 'All confirmed'} />{open.map(issue => <div className="issue" key={issue.id}><div><b>{issue.title}</b><p>{issue.evidence}</p><small>Proposed treatment: {issue.proposal}</small></div><button className="secondary" onClick={() => onConfirm(issue.id)}>Confirm treatment</button></div>)}</div><button className="primary" disabled={open.length > 0} onClick={onApprove}>{open.length ? 'Resolve issues to approve' : 'Approve RFx'}</button></div>; }
function Kicker({ children }: { children: ReactNode }) { return <div className="kicker">{children}</div> }
function SectionTitle({ title, meta }: { title: string; meta: string }) { return <div className="section-title"><h3>{title}</h3><span>{meta}</span></div> }
function ReviewSection({ title, support, children }: { title: string; support: string; children: ReactNode }) { return <section className="review-section"><div className="review-section-title"><div><h3>{title}</h3><p>{support}</p></div><span>Review</span></div>{children}</section> }
createRoot(document.getElementById('root')!).render(<App />);
